### ISSUE TITLE
"pygame.error: Invalid joystick hat" with DualShock 3

### ISSUE THREAD

**Issue by rondey** [decisionforce/metadrive#111]
Hello, 
my colleague tried to use its DualShock 3 joystick with the simulator but he encountered this error:

        Traceback (most recent call last):
          File "run_simulation.py", line 78, in <module>
            o, r, d, info = env.step([0, 0])
          File "/home/myuser/metadrive/metadrive/envs/base_env.py", line 209, in step
            engine_info = self._step_simulator(actions)
          File "/home/myuser/metadrive/metadrive/envs/base_env.py", line 235, in _step_simulator
            scene_manager_before_step_infos = self.engine.before_step(actions)
          File "/home/myuser/metadrive/metadrive/engine/base_engine.py", line 216, in before_step
            new_step_infos = manager.before_step()
          File "/home/myuser/metadrive/metadrive/manager/agent_manager.py", line 185, in before_step
            action = policy.act(agent_id)
          File "/home/myuser/metadrive/metadrive/policy/manual_control_policy.py", line 36, in act
            return self.controller.process_input(self.engine.current_track_vehicle)
          File "/home/myuser/metadrive/metadrive/engine/core/manual_controller.py", line 121, in process_input
            hat = self.joystick.get_hat(0)
        pygame.error: Invalid joystick hat

My temporal solution was this:

        try:
              hat = self.joystick.get_hat(0)
              self.button_up = True if hat[-1] == 1 else False
              self.button_down = True if hat[-1] == -1 else False
              self.button_left = True if hat[0] == -1 else False
              self.button_right = True if hat[0] == 1 else False
        except:
              self.button_up =  False
              self.button_down = False
              self.button_left = False
              self.button_right = False

I don't know if this is the right solution but it works.

**Comment by QuanyiLi** [comment]
It is ok my friend. This interface is designed for Logitech G29 and thus may bring errors when using other controllers. If you want to receive more input signals from your joystick, you can even write your own interface to read the signals from your controller/joystick.
